version: '3.8'

services:
  flask_app:
    build: .
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - flask_app
