version: '3.8'

services:
  flask_app:
    build: .
    volumes:
      - .:/app
    ports:
        - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app