name: Deploy on server

on:
  push:
    branches:
      - main  # Oder den Branch, auf den Sie deployen möchten

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/g1999emmenegger/vcid_yanik_emmenegger
            ./boot.sh
