name: Call Webhook on Push to Master

on:
  push:
    branches:
      - master

jobs:
  call-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Call webhook
      run: |
        curl -X POST http://flask.yanik.pro:8000
